### ISSUE TITLE
Consider ordering files by length rather than alphebetically

### ISSUE THREAD

**Issue by rrybarczyk** [casey/intermodal#197]
Choosing to order by alphabetical is arbitrary, and perhaps ordering by length (smallest to largest) will result in small files being "packed" into fewer pieces.

Small files in a torrent (thumbnails, descriptions, etc) are useful a lot of times and getting those together even without all the data is potentially useful.

**Comment by casey** [comment]
I thought of a potential issue with this: Sometimes files in a torrent have some kind of sequence, for example a sequence of images in a comic. The images might be different sizes though, so if imdl ordered files by length, they might be out of order.

I think this would still be good as an option, so users could pass, for example `--order alphabetical` or `--order size-ascending`, with the default being `--order alphabetical`.

**Comment by casey** [comment]
Although this probably isn't actually an issue. This would be an issue if torrent clients defaulted to downloading files in order, which they don't. Usually they default to downloading pieces rarest first. So the packing advantage of ascending size might still be advantageous.
