### ISSUE TITLE
Allow creating a `.torrent` file from a magnet link

### ISSUE THREAD

**Issue by casey** [casey/intermodal#255]
It should be possible to create a torrent file from a magnet link.

This will require connecting to the DHT and/or peers given in the link with `&x.pe=PEER`, downloading, and finally verifying the received info dictionary.

**Comment by ArtemGr** [comment]
Meanwhile, one can use aria2c to save the torrent

    aria2c --check-integrity --bt-save-metadata=true 'magnet:…'
