### ISSUE TITLE
metadata standardization

### ISSUE THREAD

**Issue by t-900-a** [casey/intermodal#327]
Hi,
I read your blog post. I like where your headed with the project and the motivation.

Have you looked at the standardized media-rss xml format?
http://www.rssboard.org/media-rss

Not sure if this is something similar that you had in mind.

**Comment by casey** [comment]
> Hi,
> I read your blog post. I like where your headed with the project and the motivation.

Thanks! I'm glad the post makes sense.

> Have you looked at the standardized media-rss xml format?
> http://www.rssboard.org/media-rss

I haven't, but it looks super interesting.

> Not sure if this is something similar that you had in mind.

It's definitely very similar. It's really interesting to see standards like this, and I think keeping them in mind will be really valuable as intermodal is developed.

I just merged #328, which adds a section to the Intermodal book for prior art related to metadata, like this one: https://imdl.io/book/metadata/prior-art.html

**Comment by casey** [comment]
Not sure if you saw, but we also have a discord server: https://discordapp.com/invite/HaaT5Qz

You might also be interest in #321, which discusses the basic design of the manifest format.
