### ISSUE TITLE
Add a page to the book discussing piece length selection

### ISSUE THREAD

**Issue by casey** [casey/intermodal#367]
I have a good comment in `piece_length_picker.rs`, but few people will probably ever see it. I should make a page in the book with the same info, both so people can refer to it, and also so that if someone has a better idea, they're more likely to see it and suggest it.

More links:
https://www.techsupportalert.com/optimizing-qbittorrent-speed
http://infinite-source.de/az/az-calc.html

**Comment by murlakatamenka** [comment]
Let's see how piece size is calculated elsewhere:

- [`libtorrent`](https://github.com/arvidn/libtorrent/blob/744e5bcfa69e60b0a552175004f6fea49901715e/src/create_torrent.cpp#L359-L390)
```cpp
		// a piece_size of 0 means automatic
		if (piece_size == 0 && !m_merkle_torrent)
		{
			// size_table is computed from the following:
			//   target_list_size = sqrt(total_size) * 2;
			//   target_piece_size = total_size / (target_list_size / hash_size);
			// Given hash_size = 20 bytes, target_piece_size = (16*1024 * pow(2, i))
			// we can determine size_table = (total_size = pow(2 * target_piece_size / hash_size, 2))
			std::array<std::int64_t, 10> const size_table{{
				       2684355LL // ->  16kiB
				,     10737418LL // ->  32 kiB
				,     42949673LL // ->  64 kiB
				,    171798692LL // -> 128 kiB
				,    687194767LL // -> 256 kiB
				,   2748779069LL // -> 512 kiB
				,  10995116278LL // -> 1 MiB
				,  43980465111LL // -> 2 MiB
				, 175921860444LL // -> 4 MiB
				, 703687441777LL}}; // -> 8 MiB


			int i = 0;
			for (auto const s : size_table)
			{
				if (s >= fs.total_size()) break;
				++i;
			}
			piece_size = default_block_size << i;
		}
		else if (piece_size == 0 && m_merkle_torrent)
		{
			piece_size = 64*1024;
		}
```

2. [`transmission`](https://github.com/transmission/transmission/blob/20119f006ca0f3a13245b379c74254c92f372910/libtransmission/makemeta.c#L89-L126)

```c
static uint32_t bestPieceSize(uint64_t totalSize)
{
    uint32_t const KiB = 1024;
    uint32_t const MiB = 1048576;
    uint32_t const GiB = 1073741824;


    if (totalSize >= 2 * GiB)
    {
        return 2 * MiB;
    }


    if (totalSize >= 1 * GiB)
    {
        return 1 * MiB;
    }


    if (totalSize >= 512 * MiB)
    {
        return 512 * KiB;
    }


    if (totalSize >= 350 * MiB)
    {
        return 256 * KiB;
    }


    if (totalSize >= 150 * MiB)
    {
        return 128 * KiB;
    }


    if (totalSize >= 50 * MiB)
    {
        return 64 * KiB;
    }


    return 32 * KiB; /* less than 50 meg */
}
```

Such a readable code :heart_eyes: !

3. [`dotorrent`](https://github.com/kz26/dottorrent/blob/fea5714efe0cde2a55eabfb387295781a78d84bb/dottorrent/__init__.py#L154-L192)

```py
    def get_info(self):
        """
        Scans the input path and automatically determines the optimal
        piece size based on ~1500 pieces (up to MAX_PIECE_SIZE) along
        with other basic info, including total size (in bytes), the
        total number of files, piece size (in bytes), and resulting
        number of pieces. If ``piece_size`` has already been set, the
        custom value will be used instead.

        :return: ``(total_size, total_files, piece_size, num_pieces)``
        """
        if os.path.isfile(self.path):
            total_size = os.path.getsize(self.path)
            total_files = 1
        elif os.path.exists(self.path):
            total_size = 0
            total_files = 0
            for x in os.walk(self.path):
                for fn in x[2]:
                    if any(fnmatch.fnmatch(fn, ext) for ext in self.exclude):
                        continue
                    fpath = os.path.normpath(os.path.join(x[0], fn))
                    fsize = os.path.getsize(fpath)
                    if fsize and not is_hidden_file(fpath):
                        total_size += fsize
                        total_files += 1
        else:
            raise exceptions.InvalidInputException
        if not (total_files and total_size):
            raise exceptions.EmptyInputException
        if self.piece_size:
            ps = self.piece_size
        else:
            ps = 1 << max(0, math.ceil(math.log(total_size / 1500, 2)))
            if ps < MIN_PIECE_SIZE:
                ps = MIN_PIECE_SIZE
            if ps > MAX_PIECE_SIZE:
                ps = MAX_PIECE_SIZE
        return (total_size, total_files, ps, math.ceil(total_size / ps))
```

`MIN_PIECE_SIZE = 2 ** 14` and `MAX_PIECE_SIZE = 2 ** 26`, so 16 KiB and 64 MiB correspondingly.

**Comment by murlakatamenka** [comment]
Some formulas need to be extracted from the code above, but the code is there.

[Torrent File Editor](https://github.com/torrent-file-editor/torrent-file-editor) can be also checked and added to the review list.

---

Vuze wiki is often the first url to appear in relevant search, but it's been last updated in 2010:
https://wiki.vuze.com/w/Torrent_Piece_Size

---

Some credible sources has instructions like this:

> Preferred piece size of a torrent depends on the size of the files included in the torrent. Size of the .torrent file is proportional to number of pieces. The more pieces, the bigger .torrent file is, and vice versa. Small piece size creates more pieces than large piece size. In general smaller .torrent is better than large one.
>
> Example:
> - 350MB file with piece size of 64kb has 5600 pieces and size of .torrent is 120kb
> - 350MB file with piece size of 256kb has 1400 pieces and size of .torrent is 30kb
>
> This rough list should help you to determine the proper piece size for your .torrents:
>
> - 32kb piece-size (for file sizes under 64MB).
> - 64kb piece-size (for file sizes from 64MB to 128MB).
> - 128kb piece-size (for file sizes from 128MB to 256MB).
> - 256kb piece-size (for file sizes from 256MB to 512MB).
> - 512kb piece-size (for file sizes from 512MB to 1024MB / 1GB).
> - 1MB piece-size (for file sizes from 1GB to 2GB).
> - 2MB piece-size (for file sizes from 2GB to 4GB).
> - 4MB piece-size (for file sizes from 4GB to 8GB).
> - 8MB piece-size (for file sizes from 8GB to 16GB).
> - 16MB piece-size (for file sizes from 16GB to 32GB).
> - 32MB piece-size ~~(for file sizes above 32GB)~~. Use **only** with very large packs which would have too large .torrent with 16MB to upload it with upload form.
> - 64MB piece-size ~~(for file sizes above 64GB)~~. Use **only** with very large packs which would have too large .torrent with 16MB or 32MB to upload it with upload form.

**Comment by murlakatamenka** [comment]
4. [Torrent File Editor](https://github.com/torrent-file-editor/torrent-file-editor/blob/811e401b38f26b6d94c4808c54ae2dcc7bbc27dd/mainwindow.cpp#L1210-L1230):

```cpp
qulonglong MainWindow::autoPieceSize() const
{
    // stripped

    qulonglong pieceSize = ui->cmbPieceSizes->itemData(ui->cmbPieceSizes->currentIndex()).toULongLong();
    // http://torrentfreak.com/how-to-make-the-best-torrents-081121/
    // Find out optimal piece size
    if (!pieceSize) {
        for (int i = 1; i < ui->cmbPieceSizes->count(); ++i) {
            pieceSize = ui->cmbPieceSizes->itemData(i).toULongLong();
            if (totalSize / pieceSize < 2000)
                break;
        }
    }
    return pieceSize;
}
```

```cpp
    ui->cmbPieceSizes->addItem(QString(), 0);
    for (int i = 5; i < 16; ++i) {
        qulonglong pieceSize = 1024 * static_cast<qulonglong>(qPow(2, i));
        ui->cmbPieceSizes->addItem(smartSize(pieceSize), pieceSize);
    }
```

So, Torrent FIles Editor relies on quite a simple strategy: keep number of pieces under 2000 with maximum piece size 16 MiB.

---

Really nice to leave a link to https://torrentfreak.com/how-to-make-the-best-torrents-081121/ as a comment :+1:
Recommendation there is to keep number of pieces within 1200-2200:

> After a number of years toying around, the optimum number of pieces seems to be between 1200 and 2200.

**Comment by casey** [comment]
Thanks for the links! I documented the algorithm, discussed the tradeoffs, and linked to references in [this page](https://imdl.io/book/bittorrent/piece-length-selection.html).
