### ISSUE TITLE
Windows installation: A positional parameter cannot be found that accepts argument '=https' error

### ISSUE THREAD

**Issue by 07416** [casey/intermodal#371]
`curl --proto '=https' --tlsv1.2 -sSf https://imdl.io/install.sh | bash`

outputs (in Powershell):

`Invoke-WebRequest : A positional parameter cannot be found that accepts argument '=https'.`

**Comment by casey** [comment]
Thanks for the report, and sorry for the issue!

It looks likeThat's interesting, it looks like calling `curl` in powershell calls `Invoke-WebRequest`, and the `=https` argument doesn't agree with it.

If you can run bash, you can try the command in bash. I think I should write a powershell-native install command, probably using `Invoke-WebRequest` directly, and put it in the readme for windows users.

**Comment by casey** [comment]
Sorry for taking so long to respond to this!

I tried to get the script to run on Windows, but ran into multiple issues. Curl is present on newer versions of windows, but on some versions, it's aliased to `Invoke-WebRequest`, plus a few commands (like `rev`) are missing that the script uses.

For now I've noted in the readme that the script only works on Linux and MacOS.

I would love to have working install script for windows, but for now I think the best way to get the binary is to download it manually from the releases page :/

**Comment by casey** [comment]
I made [this issue](https://github.com/casey/intermodal/issues/403) to track creating a `.msi` installer for windows, although I'm not sure when that'll get done.

**Comment by 07416** [comment]
Understandable, I may try the Windows 10's Linux subsystem at some point.

**Comment by casey** [comment]
I've had good luck getting rust programs to run on the WSL, so hopefully Intermodal works without issue.

**Comment by Fleshgrinder** [comment]
Anyone who has Rust installed on Windows with any toolchain can simply use `cargo install imdl` and will have it available globally. Sorry for resurrecting this old issue.
