### ISSUE TITLE
Allow input to be a positional argument

### ISSUE THREAD

**Issue by quietvoid** [casey/intermodal#375]
Hi, thank you for this tool.
I think forcing --input PATH is a little too verbose for most use cases.
Most other tools out there simply allow a named argument as well as a long option for it.

Currently, this fails:

> $ imdl torrent show myfiles.torrent

`error: Found argument 'myfiles.torrent' which wasn't expected, or isn't valid in this context`
`USAGE: imdl torrent show --input <PATH>`

structopt should support using `name = "PATH"`, however I don't know how it behaves with subcommands.

**Comment by murlakatamenka** [comment]
I pretty much agree that some simplification can be beneficial.

Actually what you ask for is to make named arguments positional ones (see [`structopt` docs](https://docs.rs/structopt/0.3.13/structopt/#specifying-argument-types)).

Subcommands in `structopt` aren't special, they are usual `struct`/`enum`'s included into main one.  Or even enum variants, as in [`git` example](https://github.com/TeXitoi/structopt/blob/master/examples/git.rs).

---

Relevant cases:

- creating torrents: `imdl create -o <output> <INPUT_FILE_OR_DIR>...`
- showing torrents: `imdl show <TORRENT>...
- completions: `imdl completions <shell_name>`. 
This is what almost any rust'y CLI utility does, including `rustup` itself!
  - `rustup completions zsh`
  - `starship init zsh` (https://starship.rs)
  - `navi widget zsh` ([navi](https://github.com/denisidoro/navi))
  - etc.

**Comment by casey** [comment]
I think this is totally reasonable. I'd like to figure out a way to do this without changing the existing usage, since I think it can be easier to remember what's what using a short or long flag.

This isn't supported directly by clap, the argument parsing library that intermodal uses, but I think it can be accomplished by using arg groups, or making the positional option conflict with the flag option.

**Comment by casey** [comment]
This is done! The following commands can take their main input as a positional argument:

`imdl torrent create`

`imdl torrent link`

`imdl torrent show`

`imdl torrent verify`

`imld completions`

The old flags still work, and will continue to work going forward, so there's no breakage with existing usage.
