### ISSUE TITLE
Add color to output

### ISSUE THREAD

**Issue by casey** [casey/intermodal#38]
Print `error` in red, message in bold. Add always/auto/never --use-color flag.

**Comment by casey** [comment]
Done!

**Comment by mustaqimM** [comment]
Hey there @casey, how do I use the flag? I tried this on `imdl v0.1.5`:
```
fd -e torrent | fzf --preview='imdl torrent show -i {} --use-color always' --height 20 --info inline
```

**Comment by casey** [comment]
Hi @mustaqimM, very cool idea to use `imdl torrent show` as a preview command for fzf!

`--use-color` is a a global option, so it should be given before the subcommand, e.g:

    imdl --use-color always show -i {}

I think you might run in to more problems though. `imdl torrent show` tries to detect if it's connected to a terminal, and if it isn't, uses a format with less decoration for the ouput. (This is so you grep and cut the output, e.g. `imdl torrent show -i foo.torrent | grep '^name' | cut -f1`.)

Using `imdl torrent show` with `fzf` makes `imdl` think it isn't connected to a terminal, which will give less attractive output. I'll add an option to disable terminal detection.

**Comment by casey** [comment]
@mustaqimM I just created the following issues to both document this use case, and add an option to actually make it work:

https://github.com/casey/intermodal/issues/397
https://github.com/casey/intermodal/issues/398

**Comment by casey** [comment]
@mustaqimM I just released v0.1.6, which supports a `--terminal` flag, which disables terminal auto-detection and forces human readable output, and added a `-c` short flag for `--color`.

I also created an FAQ with just one entry, for now, which documents how to use `imdl torrent show` with `fzf --preview`:

https://imdl.io/book/faq.html

I wanted to credit you, since I think it's a very cool use of `imdl`. Let me know if you'd prefer not to be credited!

Prebuilt binaries are now up on the [release page](https://github.com/casey/intermodal/releases), or you can build from source with `cargo install imdl`.

I tried it out, and it seems to be working well, but let me know if you run into any problems!

**Comment by mustaqimM** [comment]
@casey It works perfectly, thank you!

**Comment by casey** [comment]
Awesome, glad to hear it!
