### ISSUE TITLE
Start prior art link list for for protocols and crypto

### ISSUE THREAD

**Issue by casey** [casey/intermodal#380]
Here's an example of the kinds of links it could contain:

https://ssbc.github.io/scuttlebutt-protocol-guide/

**Comment by nijynot** [comment]
Here's some links that may or may not be of interest:
https://github.com/lightningnetwork/lightning-rfc/blob/master/08-transport.md
http://noiseprotocol.org/noise.html
https://github.com/handshake-org/hsd/blob/master/lib/net/brontide.js
https://github.com/j01tz/grin-rfcs/blob/slate-serialization/text/0000-slate-serialization.md

**Comment by casey** [comment]
Sweet, thanks! I'll definitely incorporate those. The noise protocol seems to be where it's at for e2e encryption.

**Comment by casey** [comment]
Done in https://github.com/casey/intermodal/pull/391!
