### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by DerBunteBall** [casey/intermodal#528]
What does this mean?

```
error: Failed to deserialize torrent metainfo from `./torrents/torrentfile.torrent`: Deserialization failed: data did not match any variant of untagged enum Mode
```

Transmission can work with the torrent, fetch it as magnet and so on. Fetching with magnet in intermodal also fails.

Error appers in torrent show and verify commands.

**Comment by casey** [comment]
It looks like it's failing bencode deserialization for some reason. Are you able to share the .torrent file?

**Comment by DerBunteBall** [comment]
I could provide more info via Discord DM.

**Comment by casey** [comment]
Just added you on Discord!

**Comment by casey** [comment]
Looks like this is a damaged torrent file. The `md5sum` fields, which is supposed to be hex strings, was raw bytes.
