### ISSUE TITLE
Ignore Files or Directories Manually

### ISSUE THREAD

**Issue by once375ml** [casey/intermodal#536]
I use your imdl in Synology NAS. The problem is that Synology uses directory "@eaDir" for file recording. Is there anyway to ingore the  "@eaDir" or other certain directories manually while creating torrent?

**Comment by DerBunteBall** [comment]
I think the --glob/-g option of torrent create subcommand could help you.

**Comment by once375ml** [comment]
> I think the --glob/-g option of torrent create subcommand could help you.

Like  `-g !@eadir`

Testing, hope it works!

Thank you.

**Comment by casey** [comment]
Yup, that's correct.
