### ISSUE TITLE
Feature request: compile for ARM (apple silicon) on macos

### ISSUE THREAD

**Issue by wally-crunk** [casey/intermodal#539]
When Rosetta is not installed (e.g., on a fresh install of macOS), the provided commands

> ```
> curl --proto '=https' --tlsv1.2 -sSf https://imdl.io/install.sh | bash
> cd ~/bin && ./imdl 

result in:
> zsh: bad CPU type in executable: ./imdl

- Now that macOS systems are fully switched over to ARM / Apple Silicon, it would be good to compile for this environment.  
- New systems do not ship with Rosetta installed by default.
- Compiling for ARM might marginally increase performance.

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by casey** [comment]
This is done! I just released 0.1.14, which adds prebuilt binaries for a bunch of different platforms:

https://github.com/casey/intermodal/releases/tag/v0.1.14

Let me know if it works for you!

**Comment by wally-crunk** [comment]
Tested and verified on an M1 chip with os 14.6.1! 

Thank you — Imdl is a pleasure to use.

**Comment by casey** [comment]
Nice, glad to hear it. And thank you for the kind words!
