### ISSUE TITLE
How do I announce an existing torrent?

### ISSUE THREAD

**Issue by vedantroy** [casey/intermodal#545]
I see there's a command, but I have no idea how to use it. It says my torrent's meta-info has no tracker information. Can you give an example CLI command?

**Comment by DerBunteBall** [comment]
```
imdl torrent announce -i file.torrent
```
It's possible that your torrent file really has no tracker info. This might be the case when it was fetched via a magnet-link which had no tracker parameters and the tool which fetched it didn't added a list of trackers.

I guess the announce subcommand is used to see an indication of the health of a torrent. Never used it before.

**Comment by DerBunteBall** [comment]
Tested it. It simply prints the peerlist which the tracker gives back in IP:PORT format.

Also seems that just UDP trackers are supported.

**Comment by DerBunteBall** [comment]
```
imdl torrent show -i file.torrent
```

also shows you the trackers which are in the announce-list of your torrent.

**Comment by casey** [comment]
Closing, since I think this is working.
